### ISSUE TITLE
Getting cloudflare prompts for every chapter on fanfiction.

### ISSUE THREAD

**Issue by mobedoor** [gmastergreatee/LightNovel-Manager#23]
**Describe the bug**
Instead of having to solve cloudflare captcha once, I get one prompt per chapter on Fanfiction

**To Reproduce**
Enter a fanfiction.net url
Get manual captcha page per every chapter.

**Expected behavior**
To get captcha less frequently. An option to slow chapter fetch to once per 10s/minute to look like organic behaviour.

**Comment by gmastergreatee** [comment]
Any guess on what the delay timeout should be? 10s?

This would require to change the fanfiction-rule related script

Try changing the `Ch-Script` to shown below

```
let retMe = [
  {
    "title": "",    // title of chapter
    "content": $('.storytext').html(),  // content
    "nextURL": ""
  },
];

let chap_select = document.getElementById('chap_select');
if (chap_select != null) {
    retMe[0].title = chap_select.options[chap_select.selectedIndex].text;
}

await sleep(5000);

return retMe;
```

where the line `await sleep(5000)` represents the delay between each fetched chapter
5000 milliseconds

If possible, check and tell what minimum amount of delay works for you

**Comment by gmastergreatee** [comment]
Okay, found the issue. It was happening because the chromium version being used by electron in this application is too old and needs to be updated to work properly with cloudflare.

If you are using x86-64 windows, you may download the latest version [here](https://github.com/gmastergreatee/Fanfiction-Manager/releases/download/beta_3.0.1/Fanfiction-Manager_win_x86-64_2024-09-09_0213.zip)

If there is any other problem, feel free to create another issue

Thanks
