### ISSUE TITLE
No Cover Art - Fanfiction.net

### ISSUE THREAD

**Issue by kolbdog3333** [gmastergreatee/LightNovel-Manager#3]
**Describe the bug**
When am downloading fanfic from fanficiton.net there is no cover art. Is this a bug or how do I fix it.

**Comment by kolbdog3333** [comment]
Also is there a way to export the fanfic you download as an epub

**Comment by gmastergreatee** [comment]
> Also is there a way to export the fanfic you download as an epub

Currently, there is no easy-way to export to an EPUB file. You can do it yourself if you parse the JSON files that are saved.

I had it in mind but ultimately put it on low priority because I didn't require the feature myself. If there's enough demand, I will implement it (pull-requests are welcome though). ~~Please create a separate issue regarding this.~~ -> #6 

As per the original issue, please also provide the URL of the fanfic where you found the problem.

Thank you
May you have a great day

**Comment by gmastergreatee** [comment]
FYI, fanfiction.net applies a dummy cover art for the fanfics which actually do not have any set. This dummy cover is ignored by the app currently and isn't downloaded.

For ones with the cover,  for example 
https://www.fanfiction.net/s/13646184/1/The-Witch-and-the-Sorcerer
it is downloaded

**Comment by gmastergreatee** [comment]
@kolbdog3333 Please create another issue if you face any problems.
